version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kosherhire
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: lordmaryo/kosherhire-backend:latest
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/kosherhire
    ports:
      - "8081:8081"

  frontend:
    image: lordmaryo/kosherhire-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
